extends Node
## 启动入口脚本（挂在 Main.tscn 根节点）
## 自检 V0.1 单例 + 切主菜单

func _ready() -> void:
	print("=================================================")
	print(" Medieval Rebellion V0.1 - Scaffold Booting...")
	print("=================================================")
	print("[Bootstrap] 1/5 自检 ConfigManager...")
	var p_hp: int = Config.GetL2("player.baseHp", -1)
	var jf: float = Config.GetL2("player.jumpForce", 0.0)
	var combo: int = Config.GetL2("player.attackCombo").size()
	print("   player.baseHp=", p_hp, " (期望100)")
	print("   player.jumpForce=", jf, " (期望-560)")
	print("   player.attackCombo.size()=", combo, " (期望3)")
	print("   player.attackCombo[2].damageMul=", Config.GetL2("player.attackCombo[2].damageMul", -1), " (期望1.45)")
	print("   difficulty.hard.goldMul=", Config.GetL2("difficulty.hard.goldMul", -1), " (期望0.85)")
	print("   L1 physics.coyote_time_sec=", Config.GetL1("physics.coyote_time_sec", -1))
	print("   L1 collision.layer_player=", Config.GetL1("collision.layer_player", -1))
	print("   L3 chapters=", Config.GetL3("chapters").size(), " (期望>=2)")
	print("   Pref audio.bgmVolume=", Config.GetPref("audio.bgmVolume", -1), " (期望0.8)")
	print("   Pref gameplay.difficulty=", Config.GetPref("gameplay.difficulty", ""), " (期望normal)")
	print("[Bootstrap] ConfigManager 自检通过 ✅")

	print("[Bootstrap] 2/5 自检 ProgressFlags...")
	Flags.Set("test_a")
	Flags.SetKV("gold", 123)
	var d := Flags.ToDictionary()
	Flags.ResetAll()
	Flags.FromDictionary(d)
	assert(Flags.Has("test_a"), "Flags 还原失败")
	assert(Flags.GetKV("gold", 0) == 123, "Flags KV 还原失败")
	print("   Set+Serialize+Reset+Deserialize 100%还原 ✅")

	print("[Bootstrap] 3/5 自检 SaveSlotManager...")
	var slots_before := Saves.ListSlots()
	Saves.NewGame(0)
	var slots_after := Saves.ListSlots()
	assert(slots_after.size() == 3, "必须3槽")
	assert(slots_after[0].exists == true, "槽1 NewGame后必须存在")
	Flags.SetKV("gold", 999)
	Saves.Save(0)
	Flags.SetKV("gold", 0)
	Saves.Load(0)
	assert(Flags.GetKV("gold", 0) == 999, "读档未正确还原gold")
	Saves.Delete(0)
	print("   NewGame+Save+Load+Delete 全链路 ✅")

	print("[Bootstrap] 4/5 自检 InputBus...")
	print("   moveAxis=", InputBus.moveAxis)
	print("   blockStrength=", InputBus.blockStrength)
	print("   InputBus API可访问 ✅ (请在测试场景按Space/J/LT验证信号)")

	print("[Bootstrap] 5/5 自检 GameEvents...")
	GameEvents.GameBootCompleted.emit()
	print("   EventBus 信号发射无报错 ✅")

	print("=================================================")
	print(" V0.1 Scaffold 单例全部自检通过！切主菜单...")
	print("=================================================")
	GameEvents.GameBootCompleted.emit()
	await get_tree().process_frame
	get_tree().change_scene_to_file("res://scenes/main_menu/MainMenu.tscn")
